### ISSUE TITLE
GraphQL request: Error with "Body" characters. Not honouring "Media Type"

### ISSUE THREAD

**Issue by rj-au** [datalust/seq-app-httprequest#17]
Using this Seq App has proven quite difficult, when using the "Body (Optional) field.

Attempting to use valid GraphQL syntax/query in the body:
```graphql
mutation IssueCreate {
  issueCreate(
    input: {
      title: "{@message}"
      description: "https://seq.xxxxx.io/#/events?range=1d&signal=signal-m33301,signal-30&filter=@Id%20%3D%20{@Id}"
      teamId: "xxxxxxxx-5f41-4492-9372-7cf3f699b97b"
    }
  ) {
    success
    issue {
      id
      title
    }
  }
}
```

I've tried a few values of the "Media Type (optional)" field:
* <Empty>
* `application/json`
* `text/plain`
* `application/graphql-response+json`

But get a bunch of errors, for example:

1. Quotes `"` are not supported:
> System.ArgumentException: Syntax error (line 4, column 14): unexpected `"`.
   at Seq.Syntax.Templates.ExpressionTemplate..ctor(String template, CultureInfo culture, NameResolver nameResolver, TemplateOutputEncoder encoder)
   at Seq.App.HttpRequest.HttpRequestMessageFactory..ctor(String urlTemplate, HttpMethod method, String body, Boolean bodyIsTemplate, String mediaType, List`1 headers) in C:\projects\seq-app-httprequest\src\Seq.App.HttpRequest\HttpRequestMessageFactory.cs:line 41
   at Seq.App.HttpRequest.HttpApp.OnAttached() in C:\projects\seq-app-httprequest\src\Seq.App.HttpRequest\HttpApp.cs:line 73

2. Colon `:` is not supported:
> System.ArgumentException: Syntax error (line 3, column 10): unexpected `:`, expected `)`.
   at Seq.Syntax.Templates.ExpressionTemplate..ctor(String template, CultureInfo culture, NameResolver nameResolver, TemplateOutputEncoder encoder)
   at Seq.App.HttpRequest.HttpRequestMessageFactory..ctor(String urlTemplate, HttpMethod method, String body, Boolean bodyIsTemplate, String mediaType, List`1 headers) in C:\projects\seq-app-httprequest\src\Seq.App.HttpRequest\HttpRequestMessageFactory.cs:line 41
   at Seq.App.HttpRequest.HttpApp.OnAttached() in C:\projects\seq-app-httprequest\src\Seq.App.HttpRequest\HttpApp.cs:line 73

**Comment by nblumhardt** [comment]
Hi Richard,

This is because when you select `Body is template` the whole Body field needs to be valid template syntax. Since `{` opens a placeholder in the template syntax, if you want to include a literal `{` then you'll need to double it, e.g.:

```
mutation IssueCreate {{
  issueCreate(
    input: {{
      title: "{@Message}"
      description: "https://seq.xxxxx.io/#/events?range=1d&signal=signal-m33301,signal-30&filter=@Id%20%3D%20{@Id}"
      teamId: "xxxxxxxx-5f41-4492-9372-7cf3f699b97b"
    }}
  ) {{
    success
    issue {{
      id
      title
    }}
  }}
}}
```

**Comment by nblumhardt** [comment]
Ah also, the identifier names are case-sensitive, so you'll need `@Message` rather than `@message`. (Edited above.)

**Comment by rj-au** [comment]
Great! thanks for the tips!

I also noticed I made a few more mistakes:
1. Format should be valid JSON - correction:
```json
{
  "query": "...",
  "operationName": "...", 
  "variables": {}
}
```

2. `@Message` instead of `@message`
3. Incorrect literal - use `{{`

At least this GH issue will serve as a reminder for other of what not to do.

**Comment by rj-au** [comment]
I'm still getting issues with the dollar sign `$`

The body:
```json
{{
  "operationName": "CreateLinearIssueFromSeq",
  "query": "mutation CreateLinearIssueFromSeq($input: IssueCreateInput!) { issueCreate(input: $input) {   success  } }",
  "variables": {
    "input": {
      "title": "{@Message}",
      "description": "https://seq.xxxxxxx.io/",
      "teamId": "xxxxxxxx-5f41-4492-9372-7cf3f699b97b"
    }
  }
}}
```

The JSON version:
```json
{
  "Url": "https://api.linear.app/graphql",
  "Method": "POST",
  "Body": "{{\n  \"operationName\": \"CreateLinearIssueFromSeq\",\n  \"query\": \"mutation CreateLinearIssueFromSeq($input: IssueCreateInput!) { issueCreate(input: $input) {   success  } }\",\n  \"variables\": {\n    \"input\": {\n      \"title\": \"Hubs API: {@Message}\",\n      \"description\": \"From Seq: https://seq.xxxxxx.io/\",\n      \"teamId\": \"xxxxxxx-5f41-4492-9372-7cf3f699b97b\"\n    }\n  }\n}}",
  "BodyIsTemplate": "True",
  "MediaType": "application/json",
  "AuthenticationHeader": "[seq-preserve]",
  "OtherHeaders": "",
  "ExtendedErrorDiagnostics": "True"
}
```

Error:
> System.ArgumentException: Syntax error (line 3, column 95): unexpected `$`.
   at Seq.Syntax.Templates.ExpressionTemplate..ctor(String template, CultureInfo culture, NameResolver nameResolver, TemplateOutputEncoder encoder)
   at Seq.App.HttpRequest.HttpRequestMessageFactory..ctor(String urlTemplate, HttpMethod method, String body, Boolean bodyIsTemplate, String mediaType, List`1 headers) in C:\projects\seq-app-httprequest\src\Seq.App.HttpRequest\HttpRequestMessageFactory.cs:line 41
   at Seq.App.HttpRequest.HttpApp.OnAttached() in C:\projects\seq-app-httprequest\src\Seq.App.HttpRequest\HttpApp.cs:line 73

**Comment by nblumhardt** [comment]
Hi Richard, thanks for the update.

There's still a lot of unescaped `{`s in there. They all need to be escaped, or they'll be interpreted as placeholders to replace.

If the output needs to be entirely valid JSON, you might be better off constructing an object literal:

```js
{ {
    operationName: 'CreateLinearIssueFromSeq',
    query: 'mutation CreateLinearIssueFromSeq($input: IssueCreateInput!) { issueCreate(input: $input) {   success  } }',
    variables: {
      input: {
        title: @Message,
        description: 'https://seq.xxxxxxx.io/',
        teamId: 'xxxxxxxx-5f41-4492-9372-7cf3f699b97b'
      }
    }
} }
```

This parses successfully for me. Note that the object literal version doesn't support further `{..}` placeholders, you would instead use `concat()` if you need to e.g. embed properties into strings.

The docs for this are in https://docs.datalust.co/docs/template-syntax#json-output
