### ISSUE TITLE
Requires mediaType althouth it's said to be optional

### ISSUE THREAD

**Issue by m-ocean-it** [datalust/seq-app-httprequest#9]
```
System.ArgumentException: The value cannot be null or empty. (Parameter 'mediaType')
   at System.Net.Http.Headers.MediaTypeHeaderValue.CheckMediaTypeFormat(String mediaType, String parameterName)
   at System.Net.Http.StringContent..ctor(String content, Encoding encoding, String mediaType)
   at Seq.App.HttpRequest.HttpRequestMessageFactory.FromEvent(LogEvent evt) in C:\projects\seq-app-httprequest\src\Seq.App.HttpRequest\HttpRequestMessageFactory.cs:line 57
   at Seq.App.HttpRequest.HttpApp.OnAsync(Event`1 evt) in C:\projects\seq-app-httprequest\src\Seq.App.HttpRequest\HttpApp.cs:line 84
   at SeqCli.Apps.Hosting.AppContainer.SendTypedEventAsync(String clef) in C:\projects\seqcli\src\SeqCli\Apps\Hosting\AppContainer.cs:line 121
```

**Comment by liammclennan** [comment]
Hi @m-ocean-it 

Thanks for the report. Media Type is optional for a HttpRequest app instance because it is not required unless a body is specified. If a body is specified then a media type is required as per the [HTTP specification](https://www.w3.org/Protocols/rfc2616/rfc2616-sec7.html#sec7.2.1).

Without a media type the receiving server has no way to interpret the content of the body and is instructed to treat the body as an octet stream which is probably not what is required.

If you want to send a text body you can use `text/plain`. For JSON its `application/json`. Or you can use any one of the [valid mime types](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types). 

I will update the help text to make it clear that media type is required if a body is specified.

**Comment by m-ocean-it** [comment]
Thanks! Feel free to close the issue
